version: '2'
 
services:
 
  orderer.loc.com:
    container_name: orderer.loc.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/loc.com/orderers/orderer.loc.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/loc.com/orderers/orderer.loc.com/tls/:/var/hyperledger/orderer/tls
        - orderer.loc.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
 
  peer0.intel.loc.com:
    container_name: peer0.intel.loc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.intel.loc.com
      - CORE_PEER_ADDRESS=peer0.intel.loc.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.intel.loc.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.intel.loc.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.intel.loc.com:7051
      - CORE_PEER_LOCALMSPID=IntelMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/intel.loc.com/peers/peer0.intel.loc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/intel.loc.com/peers/peer0.intel.loc.com/tls:/etc/hyperledger/fabric/tls
        - peer0.intel.loc.com:/var/hyperledger/production
    ports:
      - 7051:7051
 
  peer1.intel.loc.com:
    container_name: peer1.intel.loc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.intel.loc.com
      - CORE_PEER_ADDRESS=peer1.intel.loc.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.intel.loc.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.intel.loc.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.intel.loc.com:7051
      - CORE_PEER_LOCALMSPID=IntelMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/intel.loc.com/peers/peer1.intel.loc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/intel.loc.com/peers/peer1.intel.loc.com/tls:/etc/hyperledger/fabric/tls
        - peer1.intel.loc.com:/var/hyperledger/production
 
    ports:
      - 8051:8051
 
  peer0.lenovo.loc.com:
    container_name: peer0.lenovo.loc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.lenovo.loc.com
      - CORE_PEER_ADDRESS=peer0.lenovo.loc.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.lenovo.loc.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lenovo.loc.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.lenovo.loc.com:10051
      - CORE_PEER_LOCALMSPID=LenovoMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/lenovo.loc.com/peers/peer0.lenovo.loc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/lenovo.loc.com/peers/peer0.lenovo.loc.com/tls:/etc/hyperledger/fabric/tls
        - peer0.lenovo.loc.com:/var/hyperledger/production
    ports:
      - 9051:9051
 
  peer1.lenovo.loc.com:
    container_name: peer1.lenovo.loc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.lenovo.loc.com
      - CORE_PEER_ADDRESS=peer1.lenovo.loc.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.lenovo.loc.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.lenovo.loc.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lenovo.loc.com:9051
      - CORE_PEER_LOCALMSPID=LenovoMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/lenovo.loc.com/peers/peer1.lenovo.loc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/lenovo.loc.com/peers/peer1.lenovo.loc.com/tls:/etc/hyperledger/fabric/tls
        - peer1.lenovo.loc.com:/var/hyperledger/production
    ports:
      - 10051:10051
 
  peer0.fedex.loc.com:
    container_name: peer0.fedex.loc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.fedex.loc.com
      - CORE_PEER_ADDRESS=peer0.fedex.loc.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.fedex.loc.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fedex.loc.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.fedex.loc.com:12051
      - CORE_PEER_LOCALMSPID=FedExMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fedex.loc.com/peers/peer0.fedex.loc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fedex.loc.com/peers/peer0.fedex.loc.com/tls:/etc/hyperledger/fabric/tls
        - peer0.fedex.loc.com:/var/hyperledger/production
    ports:
      - 11051:11051
 
  peer1.fedex.loc.com:
    container_name: peer1.fedex.loc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.fedex.loc.com
      - CORE_PEER_ADDRESS=peer1.fedex.loc.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.fedex.loc.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.fedex.loc.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fedex.loc.com:11051
      - CORE_PEER_LOCALMSPID=FedExMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fedex.loc.com/peers/peer1.fedex.loc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fedex.loc.com/peers/peer1.fedex.loc.com/tls:/etc/hyperledger/fabric/tls
        - peer1.fedex.loc.com:/var/hyperledger/production
    ports:
      - 12051:12051
 
  peer0.govrelulator.loc.com:
    container_name: peer0.govrelulator.loc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.govrelulator.loc.com
      - CORE_PEER_ADDRESS=peer0.govrelulator.loc.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.govrelulator.loc.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.govrelulator.loc.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.govrelulator.loc.com:14051
      - CORE_PEER_LOCALMSPID=GovRegulatorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/govrelulator.loc.com/peers/peer0.govrelulator.loc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/govrelulator.loc.com/peers/peer0.govrelulator.loc.com/tls:/etc/hyperledger/fabric/tls
        - peer0.govrelulator.loc.com:/var/hyperledger/production
    ports:
      - 13051:13051
 
  peer1.govrelulator.loc.com:
    container_name: peer1.govrelulator.loc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.govrelulator.loc.com
      - CORE_PEER_ADDRESS=peer1.govrelulator.loc.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.govrelulator.loc.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.govrelulator.loc.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.govrelulator.loc.com:13051
      - CORE_PEER_LOCALMSPID=GovRegulatorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/govrelulator.loc.com/peers/peer1.govrelulator.loc.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/govrelulator.loc.com/peers/peer1.govrelulator.loc.com/tls:/etc/hyperledger/fabric/tls
        - peer1.govrelulator.loc.com:/var/hyperledger/production
    ports:
      - 14051:14051